### ISSUE TITLE
Open market just at specific places

### ISSUE THREAD

**Issue by realKSMC** [Xwaffle1/UniversalMarket#5]
## Environment
**Forge:** forge-1.12.2-14.23.1.2587-universal
**Sponge:** spongeforge-1.12.2-2555-7.1.0-BETA-2831

## Feature request
Pls add that you can defince places (coordinates) in config where it is just possible to open the market (I think about altars and so - RPG).

**Comment by realKSMC** [comment]
So?

**Comment by realKSMC** [comment]
Seems like the OP isn't interested in it. Closed.

**Comment by Xwaffle1** [comment]
I could incorporate this feature. Sorry for not replying, i've been quite busy lately. I've posted on Sponge, that i've been busy,
